version: "3.8"

services:
    backend:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tracker
            MYSQL_USER: trackeruser
            MYSQL_PASSWORD: trackerpass
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:
